apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: kmjayadeep/duckdns-operator:latest
    newTag: "0.1"

resources:
  - ./deployment.yaml
  - ./serviceaccount.yaml
  - ./clusterrole.yaml
  - ./clusterrolebinding.yaml

secretGenerator:
- name: duckdns
  namespace: duckdns
  envs:
  - duckdns.env
